Feature/tcp remote atf connection
Ford-Luxoft/sdl_atf pull request #2
Opened 2018-12-21 07:47 UTC by SNiukalov

Implement [Remote Automated testing](https://github.com/LuxoftAKutsan/sdl_evolution/blob/remote_atf_proxy/proposals/nnnn-remote_atf_testing.md)

This PR is **not ready** for review.

### Summary
Implement RemoteTestingAdapterServer for QNX x86

### Changelog
##### Breaking Changes
* Added implementation TCP message broker.
* Integration TCP interaction.

### Dependencies:
- [Feature/build atf using cmake](https://github.com/Ford-Luxoft/sdl_atf/pull/1)

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2019-01-15 08:45 UTC, aderiabin requested changes

2019-01-15 08:45 UTC, aderiabin commented on examples/DynamicSignalsAndSlots.lua
> +function foo()
@SNiukalov Function `foo()` is unused. Maybe it should be removed from the example.

2019-01-15 08:45 UTC, aderiabin commented on examples/DynamicSignalsAndSlots.lua
> +function d.slot_in_qt()
@SNiukalov Duplicate definition of `d.slot_in_qt()` function, previous one will be unused.

2019-01-15 08:45 UTC, aderiabin commented on modules/connecttest.lua
> +--- Remote connection and utils
@SNiukalov Current block of code duplicate one from ATF module. I propose to use ATF module instead here.

2019-01-15 08:45 UTC, aderiabin commented on modules/connecttest.lua
> +      self.applinkConnection:sendSignal(remote_application_utils.SDLMsgType.SDL_MSG_SDL_START)
@SNiukalov Is always necessary to send applink signal after start of SDL on remote host?
The `self` does not contain `applinkConnection` property here.

2019-01-15 08:45 UTC, aderiabin commented on modules/remote/remote_file_utils.lua
> +function RemoteFileUtils.mt.__index:GetFileContent(remotePathToFile, fileName)
@SNiukalov Current function returns file path to copy of file from remote host. Function should be renamed.

2019-01-15 08:45 UTC, aderiabin commented on src/remote_adapter/remote_adapter_client/lua_lib/sdl_remote_adapter_client_lua_wrapper.cc
> +      {"file_content", SDLRemoteClientLuaWrapper::lua_file_content},
@SNiukalov Current function returns file path to copy of file from remote host. Function should be renamed.

2019-01-15 08:45 UTC, aderiabin commented on src/remote_adapter/remote_adapter_client/qt_impl/sdl_remote_adapter_qt_client.cc
> +  LOG_ERROR("{0}: Websocket was not connected",__func__);
@SNiukalov Why is error message "Websocket was not connected"?

2019-01-15 08:45 UTC, aderiabin commented on modules/hmi_adapter/remote_hmi_adapter.lua
> +  -- -- ToDo (aderiabin): Add unsuccess connect check
@SNiukalov Need to implement.

2019-01-15 08:45 UTC, aderiabin commented on modules/hmi_adapter/remote_hmi_adapter.lua
> +                                            params.WebSocketConfig)
@SNiukalov Why is remote test adapter built on WebSocket here?

2019-01-15 08:45 UTC, aderiabin commented on src/remote_adapter/remote_adapter_client/qt_impl/sdl_remote_adapter_qt_client.cc
> +        emit textMessageReceived(receivedData);
@SNiukalov What is purpose of emitting `text Message Received` signal here?

2019-01-15 08:45 UTC, aderiabin commented on src/remote_adapter/remote_adapter_client/qt_impl/sdl_remote_adapter_qt_client.cc
> +    listener_ptr_ = nullptr;
@SNiukalov I think something like code below must be here instead of `listener_ptr_ = nullptr`.
```
    if(listener_ptr_){
      exitSignal_.set_value();
      listener_ptr_->join();
    }
```

2019-01-15 08:45 UTC, aderiabin commented on src/remote_adapter/remote_adapter_client/sdl_remote_adapter_client.cc
> +  const int timeout_ = 100000;
@SNiukalov Why is timeout so huge?

2019-01-15 08:45 UTC, aderiabin commented on src/remote_adapter/remote_adapter_client/lua_lib/sdl_remote_adapter_client_lua_wrapper.cc
> +      {"tcp_open", SDLRemoteClientLuaWrapper::lua_tcp_open},
@SNiukalov What purpose is of providing "tcp_*" functions? 
Besides, as I can see `tcp_*` functions provide websocket communication functions instead. I propose to rename them accordingly.

2019-01-15 08:45 UTC, aderiabin commented on src/remote_adapter/remote_adapter_client/sdl_remote_adapter_client.h
> +  int tcp_open(const std::string& address,uint32_t port);
@SNiukalov There is mismatch function name and function brief. 

The same issue occurs in all `tcp_*` functions.

2019-01-15 08:45 UTC, aderiabin commented on src/remote_adapter/remote_adapter_server/main.cc
> +  UtilsManager::StopApp("SmartDeviceLink");
@SNiukalov Are this actions really needed in all use cases of remote server on each platform?

2019-01-15 08:45 UTC, aderiabin commented on src/remote_adapter/remote_adapter_server/main.cc
> +    srv.async_run();
@SNiukalov Why does server use only one worker thread? As I understand, it is needed to use 2 worker threads (one for receive rpc and one for other "fast" rpcs) isn't it?

2019-01-16 08:29 UTC, aderiabin requested changes

2019-01-16 08:29 UTC, aderiabin commented on start.sh
> -./bin/interp modules/launch.lua $@
@SNiukalov As was discussed this script does not have to change so significantly. It must launch ATF without any additional checks.

2019-01-16 08:29 UTC, aderiabin commented on src/remote_adapter/remote_adapter_server/utils_manager.h
> +    static int StartApp(const std::string & app_path,const std::string & app_name);
@SNiukalov I propose add whitespace between parameters for all functions to improve code readability.
Example:
```
static int StartApp(const std::string & app_path,const std::string & app_name);
=>
static int StartApp(const std::string & app_path, const std::string & app_name);
```

2019-01-16 08:29 UTC, aderiabin commented on src/remote_adapter/remote_adapter_server/utils_manager.cc
> +static void *
@SNiukalov Please fix style of this file according codding style.

2019-01-16 08:29 UTC, aderiabin commented on src/remote_adapter/remote_adapter_server/tcp_message_broker.h
> +#ifndef __TCP_MESSAGE_BROKER__H__
@SNiukalov I propose to use `#pragma once` for all header files instead `#ifndef + #define`

2019-01-16 08:29 UTC, aderiabin commented on src/remote_adapter/remote_adapter_server/tcp_message_broker.cpp
> +template<typename Session>
@SNiukalov I propose to use `class` instead `typename` here to be in accordance with other methods.
```
template<typename Session> => template<class Session>
```

2019-01-16 08:29 UTC, aderiabin commented on src/remote_adapter/remote_adapter_server/tcp_message_broker.cpp
> +{
@SNiukalov Please fix style for all methods of `TCPMessageBroker<TCPListener>`
Example:
```
template<typename TCPListener>
typename TCPMessageBroker<TCPListener>::status TCPMessageBroker<TCPListener>::OpenConnection(
    const std::string& sAddress,const int port,const int threads)
{

=>

template<typename TCPListener>
typename TCPMessageBroker<TCPListener>::status TCPMessageBroker<TCPListener>::OpenConnection(
    const std::string& sAddress,const int port,const int threads) {
```

2019-01-16 08:29 UTC, aderiabin commented on modules/SDL.lua
> +    local _ = ATF.remoteUtils.file:UpdateFileContent(p, n, pContent)
@SNiukalov I propose to remove unused local variable `_`
```
 local _ = ATF.remoteUtils.file:UpdateFileContent(p, n, pContent)
=>
 ATF.remoteUtils.file:UpdateFileContent(p, n, pContent)
```

2019-01-16 08:29 UTC, aderiabin commented on modules/SDL.lua
> +local function backup(pFilePath)
@SNiukalov I propose to use `ATF.remoteUtils.file:BackupFile(remotePathToFile, fileName)` instead, for remote connection to minimize network operations.

2019-01-16 08:29 UTC, aderiabin commented on modules/SDL.lua
> +local function restore(pFilePath)
@SNiukalov I propose to use `ATF.remoteUtils.file:RestoreFile(remotePathToFile, fileName)` instead, for remote connection to minimize network operations.

2019-01-16 08:29 UTC, aderiabin commented on modules/SDL.lua
> +function SDL.BuildOptions.set()
@SNiukalov I propose to remove this function as useless.

2019-01-17 04:53 UTC, aderiabin commented on src/remote_adapter/remote_adapter_client/lua_lib/sdl_remote_adapter_client_lua_wrapper.cc
> +      {"file_content", SDLRemoteClientLuaWrapper::lua_file_content},
@aderiabin Function was renamed in lua interface module.

2019-01-17 05:10 UTC, aderiabin commented on examples/DynamicSignalsAndSlots.lua
> +function foo()
@aderiabin Function was removed in 9586a0d

2019-01-17 05:11 UTC, aderiabin commented on examples/DynamicSignalsAndSlots.lua
> +function d.slot_in_qt()
@aderiabin The function was renamed in 9586a0d

2019-01-17 05:12 UTC, aderiabin commented on modules/connecttest.lua
> +--- Remote connection and utils
@aderiabin Fixed in 9586a0d

2019-01-17 05:13 UTC, aderiabin commented on modules/connecttest.lua
> +      self.applinkConnection:sendSignal(remote_application_utils.SDLMsgType.SDL_MSG_SDL_START)
@aderiabin Code to send signal to applink was removed in 9586a0d

2019-01-17 05:14 UTC, aderiabin commented on modules/remote/remote_file_utils.lua
> +function RemoteFileUtils.mt.__index:GetFileContent(remotePathToFile, fileName)
@aderiabin The function was renamed in 9586a0d

2019-01-17 05:17 UTC, aderiabin commented on src/remote_adapter/remote_adapter_client/qt_impl/sdl_remote_adapter_qt_client.cc
> +  LOG_ERROR("{0}: Websocket was not connected",__func__);
@aderiabin Message is correct.

2019-01-17 05:18 UTC, aderiabin commented on modules/hmi_adapter/remote_hmi_adapter.lua
> +  -- -- ToDo (aderiabin): Add unsuccess connect check
@aderiabin Done in 9586a0d

2019-01-17 05:19 UTC, aderiabin commented on modules/hmi_adapter/remote_hmi_adapter.lua
> +                                            params.WebSocketConfig)
@aderiabin Construction of remote test adapter is correct.

2019-01-17 05:20 UTC, aderiabin commented on src/remote_adapter/remote_adapter_client/qt_impl/sdl_remote_adapter_qt_client.cc
> +        emit textMessageReceived(receivedData);
@SNiukalov Implementation is correct.

2019-01-17 09:59 UTC, LuxoftAKutsan approved these changes

2019-01-18 08:57 UTC, SNiukalov commented
@aderiabin  Fixed

2019-01-18 09:08 UTC, aderiabin commented on src/remote_adapter/remote_adapter_client/qt_impl/sdl_remote_adapter_qt_client.cc
> +    listener_ptr_ = nullptr;
@aderiabin Fixed in 1826a1e

2019-01-18 09:10 UTC, aderiabin commented on src/remote_adapter/remote_adapter_client/sdl_remote_adapter_client.cc
> +  const int timeout_ = 100000;
@aderiabin Fixed in 1826a1e

2019-01-18 09:13 UTC, aderiabin commented on src/remote_adapter/remote_adapter_client/lua_lib/sdl_remote_adapter_client_lua_wrapper.cc
> +      {"tcp_open", SDLRemoteClientLuaWrapper::lua_tcp_open},
@aderiabin Fixed in 1826a1e

2019-01-18 09:13 UTC, aderiabin commented on src/remote_adapter/remote_adapter_client/sdl_remote_adapter_client.h
> +  int tcp_open(const std::string& address,uint32_t port);
@aderiabin Fixed in 1826a1e

2019-01-18 09:15 UTC, aderiabin commented on src/remote_adapter/remote_adapter_server/main.cc
> +  UtilsManager::StopApp("SmartDeviceLink");
@aderiabin Fixed in 1826a1e

2019-01-18 09:18 UTC, aderiabin commented on src/remote_adapter/remote_adapter_server/main.cc
> +    srv.async_run();
@aderiabin Server ia working in asynchronous mode now.

2019-01-18 09:19 UTC, aderiabin commented on start.sh
> -./bin/interp modules/launch.lua $@
@aderiabin Fixed in 1826a1e

2019-01-18 09:20 UTC, aderiabin commented on src/remote_adapter/remote_adapter_server/utils_manager.h
> +    static int StartApp(const std::string & app_path,const std::string & app_name);
@aderiabin Fixed in 1826a1e

2019-01-18 09:22 UTC, aderiabin commented on src/remote_adapter/remote_adapter_server/tcp_message_broker.h
> +#ifndef __TCP_MESSAGE_BROKER__H__
@aderiabin Fixed in 1826a1e

2019-01-18 09:24 UTC, aderiabin commented on src/remote_adapter/remote_adapter_server/tcp_message_broker.cpp
> +template<typename Session>
@aderiabin Fixed in 1826a1e

2019-01-18 09:29 UTC, aderiabin commented on modules/SDL.lua
> +    local _ = ATF.remoteUtils.file:UpdateFileContent(p, n, pContent)
@aderiabin Fixed in 1826a1e

2019-01-18 09:29 UTC, aderiabin commented on modules/SDL.lua
> +local function restore(pFilePath)
@aderiabin Fixed in 1826a1e

2019-01-18 09:29 UTC, aderiabin commented on modules/SDL.lua
> +local function backup(pFilePath)
@aderiabin Fixed in 1826a1e

2019-01-18 09:44 UTC, aderiabin approved these changes

2019-01-18 10:18 UTC, dboltovskyi approved these changes

2019-01-18 11:24 UTC, merged